#!/usr/bin/env python3

import os
import subprocess

divider = " - "
format = "{artist}{divider}{title}"
limit = 60

def get_command_result(command) -> str:
    return subprocess.run(command, shell=True, capture_output=True, text=True).stdout.strip()

metadata = get_command_result("playerctl metadata")

players = subprocess.run("playerctl --list-all", shell=True, capture_output=True, text=True).stdout.split("\n")

# Only proceed if the player is Spotify
for player in players:
    if player.strip() != "spotify":
        continue  # Skip non-Spotify players

    status = get_command_result(f"playerctl status -p {player}")

    if status != "Stopped" and status != "":
        artist = get_command_result(f"playerctl metadata -p {player} --format '{{{{artist}}}}'")
        title = get_command_result(f"playerctl metadata -p {player} --format '{{{{title}}}}'")

        if len(artist) == 0:
            divider = ""

        text = format.replace("{title}", title).replace("{divider}", divider).replace("{artist}", artist).strip().replace("&", "&amp;").replace("{}", "")

        if len(text) > limit:
            text = f"{text[:limit - 3]}..."

        print(text, flush=True)
        exit(0)

print("", flush=True)
exit(0)

