fpath+=~/.zsh/completions

autoload -Uz compinit
autoload -Uz edit-command-line
zle -N edit-command-line

compinit

##############################################################################
# History Configuration
##############################################################################
HISTSIZE=5000               #How many lines of history to keep in memory
HISTFILE=~/.zsh_history     #Where to save history to disk
SAVEHIST=5000               #Number of history entries to save to disk
#HISTDUP=erase               #Erase duplicates in the history file
setopt    appendhistory     #Append history to the history file (no overwriting)
setopt    sharehistory      #Share history across terminals
setopt    incappendhistory  #Immediately append to the history file, not just when a term is killed


## ANTIGEN
source ~/.scripts/antigen.zsh

antigen use oh-my-zsh

antigen bundle reegnz/aws-vault-zsh-plugin
antigen bundle lukechilds/zsh-nvm
antigen bundle git
antigen bundle npm
antigen bundle encode64
antigen bundle colorize
antigen bundle github
antigen bundle bundler
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle Aloxaf/fzf-tab
antigen bundle atuinsh/atuin@main
antigen bundle MichaelAquilina/zsh-auto-notify
antigen bundle unixorn/autoupdate-antigen.zshplugin
antigen bundle reegnz/jq-zsh-plugin
antigen bundle aubreypwd/zsh-plugin-reload
antigen bundle qoomon/zsh-lazyload

antigen apply

### GLOBAL SETTINGS ###
export EDITOR="nvim"
export PATH="$PATH:$HOME/.config/scripts:$HOME/.cargo/bin:$HOME/.atuin/bin:$HOME/.spicetify:$HOME/.local/bin"

# aliases
alias gl="lazygit"
alias gowork="cd ~/dev/work/"
alias gome="cd ~/dev/personal"
alias vim="nvim"
alias nixdev="nix develop"

alias ls='exa --icons --long --git -h --group-directories-first'
alias cd='z'

alias tf="terraform"
alias aws-vault="~/.scripts/aws-vault"

alias cli-nosession="aws-vault exec hace-cli --no-session --"
alias main-nosession="aws-vault exec hace-main --no-session --"

alias awslocal="AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test AWS_DEFAULT_REGION=eu-west-2 aws --endpoint-url=http://${LOCALSTACK_HOST:-localhost}:4566"

alias parquet="~/.scripts/parquet.sh"

bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey -s '^f' "tmux-sessionizer.sh\n"
bindkey '^w' edit-command-line


eval "$(starship init zsh)"
eval "$(atuin init zsh)"
eval "$(zoxide init zsh)"

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

timezsh() {
  shell=${1-$SHELL}
  for i in $(seq 1 10); do /usr/bin/time $shell -i -c exit; done
}

. "$HOME/.atuin/bin/env"
