autoload -Uz compinit
autoload -Uz edit-command-line
zle -N edit-command-line

compinit

##############################################################################
# History Configuration
##############################################################################
HISTSIZE=5000               #How many lines of history to keep in memory
HISTFILE=~/.zsh_history     #Where to save history to disk
SAVEHIST=5000               #Number of history entries to save to disk
#HISTDUP=erase               #Erase duplicates in the history file
setopt    appendhistory     #Append history to the history file (no overwriting)
setopt    sharehistory      #Share history across terminals
setopt    incappendhistory  #Immediately append to the history file, not just when a term is killed

eval "$(starship init zsh)"
eval "$(atuin init zsh)"
eval "$(zoxide init zsh)"

### GLOBAL SETTINGS ###
export EDITOR="nvim"

# aliases
alias gl="lazygit"
alias gowork="cd ~/dev/work/"
alias gome="cd ~/dev/personal"
alias vim="nvim"
alias nixdev="nix develop"

alias ls='exa --icons --long --git -h --group-directories-first'
alias l='exa -lah --icons --group-directories-first'
alias cd='z'

alias tf="terraform"
alias cli-nosession="aws-vault exec hace-cli --no-session --"
alias main-nosession="aws-vault exec hace-main --no-session --"
alias awslocal="AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test AWS_DEFAULT_REGION=eu-west-2 aws --endpoint-url=http://${LOCALSTACK_HOST:-localhost}:4566"

alias awsvpn-connect="awsvpnclient start --config ~/.vpn/hace-main.ovpn > /dev/null 2>&1 &"
alias awsvpn-disconnect="pkill \"aws-vpn-client\""

alias flake-rebuild="nh os switch --hostname $(hostname) /home/$(whoami)/solnix"
alias flake-update="nh os switch --hostname $(hostname) --update /home/$(whoami)/solnix";
alias distro-update="sh <(curl -L https://gitlab.com/solinaire/solnix/-/raw/main/install.sh)";
alias flake-gc="nix-collect-garbage --delete-old && sudo nix-collect-garbage -d && sudo /run/current-system/bin/switch-to-configuration boot";


bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey -s '^f' "~/.scripts/tmux-sessionizer.sh\n"
bindkey '^w' edit-command-line
